apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: scheduled
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 5m" # valid cron schedule
scopes:
- catalog