apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: shopstate
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: daprworkshop-redis-master:6379
  - name: redisPassword
    value: N8IVeZRQki # Change this password